x-rabbit_envs: &rabbit_envs
  RABBITMQ_URL: "amqp://guest:guest@events-rabbitmq:5672/"
  RABBITMQ_MESSAGE_QUEUE: "Eblan_fm"


services:
  postgres:
    image: postgres:16-alpine
    container_name: events-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
      TZ: UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [events-net]

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: events-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: UTC
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: [events-net]

  events:
    build: ./backend
    container_name: events-app
    depends_on: &condition
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/events
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      JWT_SECRET: 134tfgfdg5656dgfdgd4545fsdkgffdkgdfgkdfkmbdfk342i4i24i2gdfngdngndkgdke
      <<: *rabbit_envs
    ports:
      - "8080:8080"
    networks: [events-net]

  messages_sender:
    build: ./messages-service
    depends_on:
      <<: *condition
    environment:
      <<: *rabbit_envs
      SMTP_PORT: "587"
      SMTP_HOST: "smtp.gmail.com"
      MAIL_BOX: "educational.events.itmo@gmail.com"
      MAIL_PASSWORD: "gwlmhhuciujzpbwv"
    networks: [events-net]

networks:
  events-net:

volumes:
  pgdata: