spring:
  application:
    name: events
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
        default-requeue-rejected: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          validation:
            mode: none
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    host: localhost
    port: 5432
    database: ${spring.application.name}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog.xml

jwt:
  secret: 134tfgfdg5656dgfdgd4545fsdkgffdkgdfgkdfkmbdfk342i4i24i2gdfngdngndkgdke
  access-lifetime: PT10M
  refresh-lifetime: P14D
